/*
 * UIView.java
 */

package ui;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;

import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneLayout;
import javax.swing.Timer;

import org.jdesktop.application.Action;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.TaskMonitor;

/**
 * The application's main frame.
 */
public class UIView extends FrameView implements Observer {

	public UIView(SingleFrameApplication app) {
		super(app);

		initComponents();

		ImageBrowser.currentSize = 180;

		// add the view to the list of observers
		container.addObserver(this);
		previewcontainer.addObserver(this);

		imagebrowser = new ImageBrowser(container, previewcontainer);
		JScrollPane scrollpane = new JScrollPane(imagebrowser);
		scrollpane.setLayout(new ScrollPaneLayout());
		scrollpane
				.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
		scrollpane
				.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
		scrollpane.setAlignmentX(JScrollPane.LEFT_ALIGNMENT);

		browser.setLayout(new BorderLayout());
		browser.add(scrollpane);

		// status bar initialization - message timeout, idle icon and busy
		// animation, etc
		ResourceMap resourceMap = getResourceMap();
		int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
		messageTimer = new Timer(messageTimeout, new ActionListener() {

			public void actionPerformed(ActionEvent e) {
				statusMessageLabel.setText("");
			}
		});
		messageTimer.setRepeats(false);
		int busyAnimationRate = resourceMap
				.getInteger("StatusBar.busyAnimationRate");
		for (int i = 0; i < busyIcons.length; i++) {
			busyIcons[i] = resourceMap
					.getIcon("StatusBar.busyIcons[" + i + "]");
		}
		busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {

			public void actionPerformed(ActionEvent e) {
				busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
				statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
			}
		});
		idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
		statusAnimationLabel.setIcon(idleIcon);
		progressBar.setVisible(false);

		// connecting action tasks to status bar via TaskMonitor
		TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
		taskMonitor
				.addPropertyChangeListener(new java.beans.PropertyChangeListener() {

					public void propertyChange(
							java.beans.PropertyChangeEvent evt) {
						String propertyName = evt.getPropertyName();
						if ("started".equals(propertyName)) {
							if (!busyIconTimer.isRunning()) {
								statusAnimationLabel.setIcon(busyIcons[0]);
								busyIconIndex = 0;
								busyIconTimer.start();
							}
							progressBar.setVisible(true);
							progressBar.setIndeterminate(true);
						} else if ("done".equals(propertyName)) {
							busyIconTimer.stop();
							statusAnimationLabel.setIcon(idleIcon);
							progressBar.setVisible(false);
							progressBar.setValue(0);
						} else if ("message".equals(propertyName)) {
							String text = (String) (evt.getNewValue());
							statusMessageLabel.setText((text == null) ? ""
									: text);
							messageTimer.restart();
						} else if ("progress".equals(propertyName)) {
							int value = (Integer) (evt.getNewValue());
							progressBar.setVisible(true);
							progressBar.setIndeterminate(false);
							progressBar.setValue(value);
						}
					}
				});
	}

	@Action
	public void showAboutBox(ActionEvent e) {
		if (aboutBox == null) {
			JFrame mainFrame = UIApp.getApplication().getMainFrame();
			aboutBox = new UIAboutBox(mainFrame);
			aboutBox.setLocationRelativeTo(mainFrame);
		}
		UIApp.getApplication().show(aboutBox);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		mainPanel = new javax.swing.JPanel();
		browser = new javax.swing.JPanel();
		mdi = new javax.swing.JDesktopPane();
		rightpanel = new javax.swing.JPanel();
		selections = new javax.swing.JScrollPane();
		preview = new javax.swing.JPanel();
		menuBar = new javax.swing.JMenuBar();
		javax.swing.JMenu fileMenu = new javax.swing.JMenu();
		openFileMenuItem = new javax.swing.JMenuItem();
		saveMenuItem = new javax.swing.JMenuItem();
		javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
		WindowsMenu = new javax.swing.JMenu();
		javax.swing.JMenu helpMenu = new javax.swing.JMenu();
		javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
		statusPanel = new javax.swing.JPanel();
		javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
		statusMessageLabel = new javax.swing.JLabel();
		statusAnimationLabel = new javax.swing.JLabel();
		progressBar = new javax.swing.JProgressBar();

		mainPanel.setName("mainPanel"); // NOI18N

		browser.setAutoscrolls(true);
		browser.setName("browser"); // NOI18N
		browser.setPreferredSize(new java.awt.Dimension(200, 0));

		org.jdesktop.layout.GroupLayout browserLayout = new org.jdesktop.layout.GroupLayout(
				browser);
		browser.setLayout(browserLayout);
		browserLayout.setHorizontalGroup(browserLayout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(0, 200,
				Short.MAX_VALUE));
		browserLayout.setVerticalGroup(browserLayout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(0, 380,
				Short.MAX_VALUE));

		mdi.setName("mdi"); // NOI18N

		rightpanel.setName("rightpanel"); // NOI18N

		selections.setFocusable(false);
		selections.setName("selections"); // NOI18N

		org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application
				.getInstance(ui.UIApp.class).getContext().getResourceMap(
						UIView.class);
		//preview.setBorder(javax.swing.BorderFactory
		//		.createTitledBorder(resourceMap
		//				.getString("preview.border.title"))); // NOI18N
		preview.setName("preview"); // NOI18N

		org.jdesktop.layout.GroupLayout previewLayout = new org.jdesktop.layout.GroupLayout(
				preview);
		preview.setLayout(previewLayout);
		previewLayout.setHorizontalGroup(previewLayout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(0, 180,
				Short.MAX_VALUE));
		previewLayout.setVerticalGroup(previewLayout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(0, 160,
				Short.MAX_VALUE));

		org.jdesktop.layout.GroupLayout rightpanelLayout = new org.jdesktop.layout.GroupLayout(
				rightpanel);
		rightpanel.setLayout(rightpanelLayout);
		rightpanelLayout.setHorizontalGroup(rightpanelLayout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(selections,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 196,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(
						preview,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE));
		rightpanelLayout.setVerticalGroup(rightpanelLayout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				org.jdesktop.layout.GroupLayout.TRAILING,
				rightpanelLayout.createSequentialGroup().add(preview,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED).add(
								selections,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								237, Short.MAX_VALUE)));

		org.jdesktop.layout.GroupLayout mainPanelLayout = new org.jdesktop.layout.GroupLayout(
				mainPanel);
		mainPanel.setLayout(mainPanelLayout);
		mainPanelLayout
				.setHorizontalGroup(mainPanelLayout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								mainPanelLayout
										.createSequentialGroup()
										.add(
												browser,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(mdi)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.UNRELATED)
										.add(
												rightpanel,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)));
		mainPanelLayout.setVerticalGroup(mainPanelLayout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(rightpanel,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.add(org.jdesktop.layout.GroupLayout.TRAILING, mdi).add(
						browser, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						380, Short.MAX_VALUE));

		menuBar.setName("menuBar"); // NOI18N

		fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
		fileMenu.setName("fileMenu"); // NOI18N

		openFileMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_O,
				java.awt.event.InputEvent.CTRL_MASK));
		openFileMenuItem
				.setText(resourceMap.getString("openFileMenuItem.text")); // NOI18N
		openFileMenuItem.setName("openFileMenuItem"); // NOI18N
		openFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				openFileMenuItemActionPerformed(evt);
			}
		});
		fileMenu.add(openFileMenuItem);

		saveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_S,
				java.awt.event.InputEvent.CTRL_MASK));
		saveMenuItem.setText(resourceMap.getString("saveMenuItem.text")); // NOI18N
		saveMenuItem.setName("saveMenuItem"); // NOI18N
		saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				saveMenuItemActionPerformed(evt);
			}
		});
		fileMenu.add(saveMenuItem);

		javax.swing.ActionMap actionMap = org.jdesktop.application.Application
				.getInstance(ui.UIApp.class).getContext().getActionMap(
						UIView.class, this);
		exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
		exitMenuItem.setName("exitMenuItem"); // NOI18N
		fileMenu.add(exitMenuItem);

		menuBar.add(fileMenu);

		WindowsMenu.setText(resourceMap.getString("WindowsMenu.text")); // NOI18N
		WindowsMenu.setName("WindowsMenu"); // NOI18N
		menuBar.add(WindowsMenu);

		helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
		helpMenu.setName("helpMenu"); // NOI18N

		aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
		aboutMenuItem.setName("aboutMenuItem"); // NOI18N
		helpMenu.add(aboutMenuItem);

		menuBar.add(helpMenu);

		statusPanel.setName("statusPanel"); // NOI18N

		statusMessageLabel.setName("statusMessageLabel"); // NOI18N

		statusAnimationLabel
				.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

		progressBar.setName("progressBar"); // NOI18N

		org.jdesktop.layout.GroupLayout statusPanelLayout = new org.jdesktop.layout.GroupLayout(
				statusPanel);
		statusPanel.setLayout(statusPanelLayout);
		statusPanelLayout
				.setHorizontalGroup(statusPanelLayout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(statusPanelSeparator,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								828, Short.MAX_VALUE)
						.add(
								statusPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.add(statusMessageLabel)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED,
												632, Short.MAX_VALUE)
										.add(
												progressBar,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(statusAnimationLabel)
										.addContainerGap()));
		statusPanelLayout
				.setVerticalGroup(statusPanelLayout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								statusPanelLayout
										.createSequentialGroup()
										.add(
												statusPanelSeparator,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												2,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.add(
												statusPanelLayout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(statusMessageLabel)
														.add(
																statusAnimationLabel)
														.add(
																progressBar,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.add(3, 3, 3)));

		setComponent(mainPanel);
		setMenuBar(menuBar);
		setStatusBar(statusPanel);
	}// </editor-fold>//GEN-END:initComponents

	private void openFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_openFileMenuItemActionPerformed
		menuCtrl.openFile(imagebrowser);
	}// GEN-LAST:event_openFileMenuItemActionPerformed

	private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_saveMenuItemActionPerformed
		// TODO
		if(mdi.getSelectedFrame() != null) {
			menuCtrl.saveFile(null);
		}		
	}// GEN-LAST:event_saveMenuItemActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	protected static javax.swing.JMenu WindowsMenu;
	private javax.swing.JPanel browser;
	private javax.swing.JPanel mainPanel;
	private javax.swing.JDesktopPane mdi;
	private javax.swing.JMenuBar menuBar;
	private javax.swing.JMenuItem openFileMenuItem;
	private javax.swing.JPanel preview;
	private javax.swing.JProgressBar progressBar;
	private javax.swing.JPanel rightpanel;
	private javax.swing.JMenuItem saveMenuItem;
	private javax.swing.JScrollPane selections;
	private javax.swing.JLabel statusAnimationLabel;
	private javax.swing.JLabel statusMessageLabel;
	private javax.swing.JPanel statusPanel;
	// End of variables declaration//GEN-END:variables
	private final Timer messageTimer;
	private final Timer busyIconTimer;
	private final Icon idleIcon;
	private final Icon[] busyIcons = new Icon[15];
	private int busyIconIndex = 0;
	private JDialog aboutBox;

	private ImageFramesContainer container = new ImageFramesContainer();

	private PreviewContainer previewcontainer = new PreviewContainer();

	private MenuController menuCtrl = new MenuController();

	private ImageBrowser imagebrowser;
	
	public void update(Observable arg0, Object arg1) {

		if (arg0 instanceof PreviewContainer) {
			BufferedImage img = previewcontainer.getScaledImage();
			
			//clean old preview
			preview.getGraphics().clearRect(0, 0, preview.getWidth(), preview.getHeight());
			
			if(img != null) {
				System.out.println("UIView.update replace preview");
				preview.getGraphics().drawImage(img,0,0,null);
			} 			
		}

		if (arg0 instanceof ImageFramesContainer) {
			// keep a copy of the components
			ArrayList<ImageFrame> mdiframes = new ArrayList<ImageFrame>();

			// remove old frames
			if (mdi.getComponents().length > 0) {
				for (int i = 0; i < mdi.getComponents().length; i++) {
					ImageFrame frame = (ImageFrame) mdi.getComponent(i);
					if (!container.contains(frame)) {
						System.out.println("UIView.update remove frame");
						mdi.remove(frame);
					} else {
						mdiframes.add(frame);
					}
				}
			}

			// add new frames
			for (ImageFrame frame : container.getFrames()) {
				if (!mdiframes.contains(frame)) {
					System.out.println("UIView.update add frame");
					
					frame.setMenuItem(new WindowItem(frame, mdi));
					
					UIView.WindowsMenu.add(frame.getMenuItem());
					mdi.add(frame);
					mdi.getDesktopManager().activateFrame(frame);
				}
			}

			mdiframes = null;
		}
	}
}